openapi: 3.0.1
info:
  title: Arduino Temperature API
  description: An API for managing temperature data, including fetching data by category, time interval, and aggregated information.
  version: 'v1'
servers:
  - url: https://arduino-temp-api.replit.app/
    description: Replit Environment

paths:
  /temperature/fetch_data:
    get:
      operationId: fetchTemperatureData
      summary: Fetch recent temperature data
      parameters:
        - name: limit
          in: query
          description: Number of records to return
          required: false
          schema:
            type: integer
            default: 10
      responses:
        "200":
          description: List of temperature data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TemperatureData'

  /temperature/by_category:
    get:
      operationId: getTemperaturesByCategory
      summary: Get temperatures by category
      parameters:
        - name: category
          in: query
          description: Temperature category (låg, hög, stabil)
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Temperature data for the specified category
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TemperatureData'
        "400":
          description: Invalid category

  /temperature/time_interval:
    get:
      operationId: getDataByTimeInterval
      summary: Get temperature data by time interval
      parameters:
        - name: interval
          in: query
          description: Time interval (minutes, hours, days)
          required: true
          schema:
            type: string
        - name: amount
          in: query
          description: Amount of time to look back
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Temperature data for the specified time interval
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TemperatureData'
        "400":
          description: Invalid time interval

  /temperature/aggregated:
    get:
      operationId: getAggregatedData
      summary: Get aggregated temperature data
      parameters:
        - name: start_date
          in: query
          description: Start date for aggregation (YYYY-MM-DD HH:MM)
          required: true
          schema:
            type: string
            format: date-time
        - name: end_date
          in: query
          description: End date for aggregation (YYYY-MM-DD HH:MM)
          required: true
          schema:
            type: string
            format: date-time
        - name: aggregation_type
          in: query
          description: Type of aggregation (max, min, average)
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Aggregated temperature data
          content:
            application/json:
              schema:
                type: object
                properties:
                  average_temperature:
                    type: number
                  maximum_temperature:
                    type: number
                  minimum_temperature:
                    type: number
        "400":
          description: Invalid aggregation type or datetime format

components:
  schemas:
    TemperatureData:
      type: object
      properties:
        temperature:
          type: number
          description: Temperature value
        tempCategory:
          type: string
          description: Category of the temperature
        ledColor:
          type: string
          description: LED color corresponding to the temperature
        timestamp:
          type: string
          format: date-time
          description: Timestamp of the temperature data
